import { Google_Sans_Flex } from "next/font/google";
import "./globals.css";

const googleSansFlex = Google_Sans_Flex({
  style: "normal",
  subsets: ["latin"],
  variable: "--font-google-sans-flex",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${googleSansFlex.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
